name: minigpt4
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - python=3.10
  - cudatoolkit
  - pip
  - pytorch
  - pytorch-mutex=1.0=cuda
  - torchaudio
  - torchvision
  - pip:
    - accelerate
    - aiohttp
    - aiosignal
    - async-timeout
    - attrs
    - bitsandbytes
    - cchardet
    - chardet
    - contourpy
    - cycler
    - filelock
    - fonttools
    - frozenlist
    - huggingface-hub
    - importlib-resources
    - kiwisolver
    - matplotlib
    - multidict
    - openai
    - packaging
    - psutil
    - pycocotools
    - pyparsing
    - python-dateutil
    - pyyaml
    - regex
    - tokenizers
    - tqdm
    - transformers
    - timm
    - spacy
    - webdataset
    - scikit-learn
    - scipy
    - yarl
    - zipp
    - omegaconf
    - opencv-python
    - iopath
    - decord
    - tenacity
    - peft
    - pycocoevalcap
    - sentence-transformers
    - umap-learn
    - notebook
    - gradio
    - gradio-client
    - wandb
